apiVersion: v1
kind: Service
metadata:
  name: backend-feed 
  labels:
    service: backend-feed
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
    protocol: "TCP"
  selector:
    service: backend-feed