apiVersion: v1
kind: Service
metadata:
  name: backend-feed-svc
  labels:
    service: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: "TCP"
  selector:
    service: backend-feed