apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    service: reverseproxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
    protocol: "TCP"
  selector:
    service: reverseproxy